name: Stop SQL Instance
on:
  schedule:
    - cron: '0 1 * * *'  # 01:00 UTC = 22:00 Argentina
jobs:
  stop-sql:
    runs-on: ubuntu-latest
    steps:
      - name: Setup gcloud
        uses: google-github-actions/setup-gcloud@v2
        with:
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          project_id: learned-maker-459200-v6
      - name: Stop SQL instance
        run: gcloud sql instances patch mi-instancia-sql --activation-policy NEVER
