name: Start SQL Instance

on:
  push:
    branches:
      - main
      
  workflow_dispatch:
  schedule:
    - cron: '0 11 * * *'
jobs:
  start-sql:
    runs-on: ubuntu-latest
    steps:
      - name: Setup gcloud
        uses: google-github-actions/setup-gcloud@v2
        with:
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          project_id: learned-maker-459200
      - name: Start SQL instance
        run: gcloud sql instances start mi-instancia-sql
