name: Stop SQL

on:
  schedule:
    - cron: '0 23 * * *'  # 8PM Argentina (UTC+3)
  workflow_dispatch:      # Permite ejecutarlo manualmente desde GitHub

jobs:
  stop-sql:
    runs-on: ubuntu-latest

    steps:
      - uses: 'google-github-actions/auth@v2'
        with:
          credentials_json: '${{ secrets.GCP_SA_KEY }}'

      - uses: 'google-github-actions/setup-gcloud@v2'
        with:
          project_id: 'learned-maker-459200-v6'

      - name: Stop SQL instance
        run: gcloud sql instances patch mi-instancia-sql --activation-policy=NEVER



