name: Stop SQL Instances (Weekends)

on:
  schedule:
    - cron: '0 1 * * 6,0'  # 10 PM Argentina (UTC-3) del Sábado y Domingo (para asegurar que estén apagadas al final del día)
  workflow_dispatch:      # Permite ejecución manual

jobs:
  stop-sql-instances:
    runs-on: ubuntu-latest
    steps:
      - name: Authenticate to Google Cloud
        uses: 'google-github-actions/auth@v2'
        with:
          credentials_json: '${{ secrets.GCP_SA_KEY }}'

      - name: Set up Google Cloud CLI
        uses: 'google-github-actions/setup-gcloud@v2'
        with:
          project_id: 'learned-maker-459200-v6'

      - name: Stop All SQL Instances If Running
        run: |
          PROJECT_ID="learned-maker-459200-v6"
          INSTANCES=("mi-instancia-sql" "instancia-sql-2")

          for INSTANCE_NAME in "${INSTANCES[@]}"; do
            echo "Checking state of $INSTANCE_NAME..."
            STATE=$(gcloud sql instances describe "$INSTANCE_NAME" --project="$PROJECT_ID" --format="value(state)")
            if [ "$STATE" == "RUNNABLE" ]; then
              echo "Instance $INSTANCE_NAME is running. Stopping..."
              gcloud sql instances patch "$INSTANCE_NAME" --project="$PROJECT_ID" --activation-policy=NEVER
              echo "Instance $INSTANCE_NAME set to NEVER (stopped)."
            else
              echo "Instance $INSTANCE_NAME is already stopped. Skipping."
            fi
          done
