name: Stop SQL Instances

on:
  schedule:
    - cron: '0 23 * * 5,6'  # 8PM Argentina (UTC-3) - Se ejecuta sábados y domingos
  workflow_dispatch:      # Permite ejecutarlo manualmente desde GitHub

jobs:
  stop-sql-instances:
    runs-on: ubuntu-latest

    steps:
      - name: Authenticate to Google Cloud
        uses: 'google-github-actions/auth@v2'
        with:
          credentials_json: '${{ secrets.GCP_SA_KEY }}'

      - name: Set up Google Cloud CLI
        uses: 'google-github-actions/setup-gcloud@v2'
        with:
          project_id: 'learned-maker-459200-v6'

      - name: Stop SQL Instance 1
        run: |
          INSTANCE_NAME="mi-instancia-sql" # Reemplaza con el nombre de tu primera instancia
          echo "Attempting to stop instance: $INSTANCE_NAME"
          gcloud sql instances patch "$INSTANCE_NAME" --activation-policy=NEVER
          echo "Successfully requested stop for instance: $INSTANCE_NAME"

      - name: Stop SQL Instance 2
        run: |
          INSTANCE_NAME="instancia-sql-2" # Reemplaza con el nombre de tu segunda instancia
          echo "Attempting to stop instance: $INSTANCE_NAME"
          gcloud sql instances patch "$INSTANCE_NAME" --activation-policy=NEVER
          echo "Successfully requested stop for instance: $INSTANCE_NAME"



